import { EyeOff, FlaskConical, Gauge, Radio, type LucideIcon } from 'lucide-react'
import { cn } from '@/lib/cn'
import { toneClasses } from '@/lib/theme'
import { Badge, Panel, PanelHeader, Skeleton } from '@/components/ui'
import { useDataSource } from '@/store'
import type { DataSourceInfo } from '@/types'
import { dataSourceModeMeta } from './utils'

const DISCLOSURE: { icon: LucideIcon; text: string }[] = [
  {
    icon: FlaskConical,
    text: 'Traffic, devices, threats and events are generated by the NEXUS simulation engine — nothing is captured from a real network.',
  },
  {
    icon: Gauge,
    text: 'Model performance figures come from a simulated evaluation. They are prototype values, not results from real experiments.',
  },
  {
    icon: EyeOff,
    text: 'External addresses are partially masked, so no activity is attributed to a real host.',
  },
]

interface DataSourcePanelProps {
  /** Used until the live store has the data source (e.g. from GET /api/system). */
  fallback?: DataSourceInfo
  className?: string
}

/** Where NEXUS telemetry comes from, with an explicit simulation disclosure. */
export function DataSourcePanel({ fallback, className }: DataSourcePanelProps) {
  const source = useDataSource() ?? fallback ?? null
  const meta = source ? dataSourceModeMeta[source.mode] : null
  const simulated = source?.mode === 'simulation'
  const t = toneClasses[meta?.tone ?? 'violet']

  return (
    <Panel className={className}>
      <PanelHeader
        eyebrow="Data source"
        title={source?.label ?? 'Data source'}
        icon={simulated || !source ? FlaskConical : Radio}
        iconTone={meta?.tone ?? 'violet'}
        actions={
          meta && (
            <Badge tone={meta.tone} dot>
              {meta.label}
            </Badge>
          )
        }
      />

      {!source ? (
        <div className="space-y-2" aria-busy>
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-3/4" />
          <Skeleton className="mt-4 h-24 w-full rounded-lg" />
        </div>
      ) : (
        <>
          <p className="text-sm leading-relaxed text-ink-2">{source.description}</p>
          {simulated && (
            <div className={cn('mt-4 rounded-lg border p-4', t.softBorder, 'bg-void/40')}>
              <p className={cn('eyebrow mb-3', t.text)}>Simulation disclosure</p>
              <ul className="space-y-2.5">
                {DISCLOSURE.map(({ icon: Icon, text }) => (
                  <li key={text} className="flex gap-2.5 text-xs leading-relaxed text-muted">
                    <Icon className={cn('mt-0.5 size-3.5 shrink-0', t.text)} strokeWidth={1.75} aria-hidden />
                    {text}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}
    </Panel>
  )
}
