"""System information: data source disclosure, defaults and the pipeline module registry."""

from __future__ import annotations

from app import __version__
from typing import Any

from app.schemas import DataSourceInfo, DefenseSettings, EngineModule, ModuleStatus, SystemInfo

DATA_SOURCE = DataSourceInfo(
    mode="simulation",
    label="Simulated environment",
    description="All telemetry is generated by the NEXUS simulation engine — no real network traffic is captured in this prototype.",
)


def default_settings() -> DefenseSettings:
    return DefenseSettings(
        autonomous_mode=True,
        auto_response_threshold=70,
        quarantine_threshold=85,
        anomaly_threshold=0.72,
        notify_administrator=True,
        detection_sensitivity="balanced",
    )


MODULES = (
    EngineModule(key="capture", name="Packet capture", stage="Network Traffic", technology="Scapy", status="simulated", description="A synthetic flow generator stands in for live packet capture."),
    EngineModule(key="features", name="Flow feature extraction", stage="Feature Extraction", technology="CICFlowMeter-style features", status="simulated", description="Per-flow statistics (rates, ratios, entropy) are produced by the simulator."),
    EngineModule(key="classifier", name="Supervised classifier", stage="AI Threat Detection", technology="XGBoost / Random Forest", status="simulated", description="Attack classes and confidences are simulated; the interface matches a trained model."),
    EngineModule(key="anomaly", name="Anomaly detector", stage="Anomaly Detection", technology="Isolation Forest / Autoencoder", status="simulated", description="Anomaly scores come from the traffic model instead of a fitted detector."),
    EngineModule(key="explainer", name="Explainability", stage="Explainable AI", technology="SHAP", status="simulated", description="Feature attributions are generated consistently with each simulated detection."),
    EngineModule(key="graph", name="Graph analysis", stage="Network relationship analysis", technology="NetworkX / GNN", status="planned", description="Relationship analysis across hosts and flows is planned for a later phase."),
    EngineModule(key="store", name="Event store", stage="Security events", technology="PostgreSQL", status="ready", description="Events live in an in-memory repository; the schema and repository interface are ready for PostgreSQL."),
    EngineModule(key="api", name="REST API", stage="Frontend → API", technology="FastAPI", status="active", description="The frontend reads every view from this FastAPI service."),
    EngineModule(key="realtime", name="Realtime transport", stage="Visualization", technology="WebSocket (+ polling fallback)", status="active", description="A sequenced event log pushes every change over /ws/events; HTTP polling takes over if WebSockets are unavailable."),
    EngineModule(key="simulator", name="Attack simulator", stage="Demonstration", technology="Scenario engine", status="active", description="Stages synthetic attacks through the full detect → explain → respond pipeline against the simulated network."),
    EngineModule(key="assistant", name="Security assistant", stage="Security Assistant", technology="LLM-ready (rule-based today)", status="simulated", description="A rule-based analyst answers from live state; an LLM provider can be plugged in."),
    EngineModule(key="federated", name="Federated learning", stage="Learn", technology="FedAvg", status="simulated", description="Three simulated clients train locally and share model updates only."),
    EngineModule(key="dp", name="Differential privacy", stage="Learn", technology="DP-SGD (Gaussian)", status="simulated", description="Clipping and noise parameters are modelled; no real training runs yet."),
)


def system_info(live: Any = None, llm: Any = None) -> SystemInfo:
    """Module registry, upgraded with the real components that are installed or running."""
    modules = {m.key: m for m in MODULES}
    source = DATA_SOURCE
    if live is not None:
        running = bool(live.running)
        ready = bool(live.models.ready)
        baseline = "this network's" if live.models.info.benign_source == "live" else "generic"
        from app.live.capture import capture_available

        driver, _ = capture_available()
        cap: ModuleStatus = "active" if running else ("ready" if driver else "simulated")
        det: ModuleStatus = "active" if running and ready else "ready"
        modules["capture"] = modules["capture"].model_copy(update={"status": cap, "technology": "Scapy + Npcap", "description": f"Captures packet headers on {live.interface}; payloads are never stored." if driver else "Scapy is installed but no capture driver was found (install Npcap); synthetic flows are used meanwhile."})
        modules["features"] = modules["features"].model_copy(update={"status": cap, "technology": "5 s host windows · 15 features", "description": "Per-host rates, port/host diversity, SYN/RST ratios, DNS entropy and NXDOMAIN share, inbound fan-in."})
        modules["classifier"] = modules["classifier"].model_copy(update={"status": det, "technology": "XGBoost (multi-class)", "description": f"Classifies live host windows; trained on {baseline} benign traffic plus synthetic attack profiles. Featured incidents and the simulator stay simulated."})
        modules["anomaly"] = modules["anomaly"].model_copy(update={"status": det, "technology": "Isolation Forest", "description": f"Scores every live window against the {baseline} benign baseline."})
        modules["explainer"] = modules["explainer"].model_copy(update={"status": det, "technology": "SHAP TreeExplainer", "description": "Real SHAP attributions explain every live detection; simulated incidents use spec values."})
        source = live.data_source() or DATA_SOURCE
    if llm is not None and "assistant" in modules:
        modules["assistant"] = modules["assistant"].model_copy(update={"status": "active", "technology": f"Groq · {llm.model}", "description": "The LLM narrates facts gathered from NEXUS state. It has no tools and cannot execute actions; it falls back to the rule-based analyst."})
    return SystemInfo(version=__version__, data_source=source, modules=list(modules.values()))
