import type { ThreatDetail } from '@/types'

/** Plain-language incident report for one threat, as Markdown. */
export function threatReportMarkdown(t: ThreatDetail, generatedAt = new Date()): string {
  const line = (label: string, value: string | number | null | undefined) => `| ${label} | ${value ?? '—'} |`
  const parts = [
    `# Incident report — ${t.name} (${t.id})`,
    '',
    `Generated by NEXUS on ${generatedAt.toLocaleString()}.`,
    '',
    '## Summary',
    '',
    t.explanation,
    '',
    '| Field | Value |',
    '| --- | --- |',
    line('Severity', t.severity),
    line('Status', t.status.replace(/_/g, ' ')),
    line('Risk score', `${t.riskScore} / 100`),
    line('Model confidence', `${t.confidence.toFixed(1)}%`),
    line('Source', `${t.sourceLabel} (${t.sourceIp})`),
    line('Target', `${t.targetLabel} (${t.targetIp})`),
    line('Detected', new Date(t.timestamp).toLocaleString()),
    line('Response time', t.responseTimeMs !== null ? `${t.responseTimeMs} ms` : 'not contained'),
    line('Detected by', t.detectedBy.join(', ')),
    line('MITRE ATT&CK', t.mitre ? `${t.mitre.id} · ${t.mitre.name} (${t.mitre.tactic})` : null),
    '',
    '## Why NEXUS flagged it',
    '',
    '| Feature | Observed | Baseline | Contribution |',
    '| --- | --- | --- | --- |',
    ...t.features.map((f) => `| ${f.label} | ${f.observed} | ${f.baseline} | ${f.contribution >= 0 ? '+' : ''}${f.contribution.toFixed(2)} |`),
    '',
    '## Risk factors',
    '',
    '| Factor | Value | Weight |',
    '| --- | --- | --- |',
    ...t.riskFactors.map((r) => `| ${r.label} | ${r.value} | ${Math.round(r.weight * 100)}% |`),
    '',
    '## Timeline',
    '',
    ...t.timeline.map((s) => `- **+${(s.offsetMs / 1000).toFixed(1)} s — ${s.label}.** ${s.detail}`),
    '',
    '## Response actions',
    '',
    ...(t.actions.length ? t.actions.map((a) => `- ${a.label} → ${a.target} (${a.status})${a.detail ? ` — ${a.detail}` : ''}`) : ['- None']),
    '',
    '---',
    'NEXUS research prototype. Enforcement actions are simulated; verify before acting on this report.',
    '',
  ]
  return parts.join('\n')
}

export function downloadText(filename: string, text: string, type = 'text/markdown') {
  const url = URL.createObjectURL(new Blob([text], { type }))
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/** Open a print-ready copy of the report; the browser's print dialog saves it as PDF. */
export function printReport(markdown: string, title: string) {
  const html = markdown
    .split('\n')
    .map((l) => {
      if (l.startsWith('# ')) return `<h1>${escape(l.slice(2))}</h1>`
      if (l.startsWith('## ')) return `<h2>${escape(l.slice(3))}</h2>`
      if (l.startsWith('| ---')) return ''
      if (l.startsWith('|')) return `<tr>${l.split('|').slice(1, -1).map((c) => `<td>${escape(c.trim())}</td>`).join('')}</tr>`
      if (l.startsWith('- ')) return `<li>${escape(l.slice(2)).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')}</li>`
      if (l === '---') return '<hr>'
      return l ? `<p>${escape(l)}</p>` : ''
    })
    .join('\n')
    .replace(/((?:<tr>.*<\/tr>\n?)+)/g, '<table>$1</table>')
    .replace(/((?:<li>.*<\/li>\n?)+)/g, '<ul>$1</ul>')
  const w = window.open('', '_blank')
  if (!w) return false
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escape(title)}</title>
<style>body{font:14px/1.5 system-ui,sans-serif;color:#111;max-width:760px;margin:32px auto;padding:0 16px}h1{font-size:22px}h2{font-size:16px;margin-top:24px}
table{border-collapse:collapse;width:100%;margin:8px 0}td{border:1px solid #ccc;padding:4px 8px;vertical-align:top}tr:first-child td{font-weight:600;background:#f3f4f6}hr{margin-top:24px}</style>
</head><body>${html}<script>window.onload=()=>window.print()</script></body></html>`)
  w.document.close()
  return true
}
